/* WEEKLY GLOBAL LANGUAGES — Vol.1 / 2026-W36 : 号の骨格 */
WGL.registerIssue({

  meta: {
    volume: '1',
    title: 'WEEKLY GLOBAL LANGUAGES',
    dateRange: '2026年8月26日 — 9月1日',
    published: '2026-09-01'
  },

  sectionTitles: {
    en: { title: 'ENGLISH WORLD', sub: '英語圏と国際ニュース ― ビジネス、そして天気の話' },
    zh: { title: '中文世界',       sub: '中国・中国語圏 ― エネルギー、そして「言語を選ぶ」ということ' },
    es: { title: 'MUNDO EN ESPAÑOL', sub: 'スペインとラテンアメリカ ― 別れの言葉と、タコのピザ' },
    fr: { title: 'LE MONDE FRANCOPHONE', sub: 'フランス語圏 ― 9月1日、フランスが一斉に動き出す日' }
  },

  cover: {
    title: 'One company, four languages: the day Shein met the world',
    ja: 'ひとつの会社、四つの言語 ― シーインが世界と向き合った日',
    lead: [
      '2026年9月1日。香港の証券取引所で銅鑼が鳴り、シーインの株式がついに取引を開始しました。かつて「1000億ドル企業」と語られた会社の値づけは、その4分の1。株価は取引開始直後に10%下落しました。',
      'その同じ日、パリでは官報に載った一枚の省令が動き出していました。シーイン、テム、アリエクスプレスが売るような「超使い捨てファッション」に、環境スコアに応じた課金を課す制度です。Tシャツ1枚につき2ユーロ。',
      '資本市場が迎え入れる手と、規制が押し戻す手。同じ産業に、同じ日に、正反対の力が働きました。そしてこの出来事は、英語では「投資家の食指」の話として、フランス語では「使い捨て文化」の話として、中国語では「中国企業の海外展開」の話として、スペイン語では「株価が10%下落した」という一行として報じられました。',
      '同じ事実を、四つの言語で読む。すると、事実は同じでも、どこに枠を当てるかで見える絵が違うことが分かります ― それが、この雑誌をつくった理由です。'
    ]
  },

  /* ── THE WORLD THIS WEEK ─────────────────────────────── */
  worldThisWeek: [
    { lang: 'en', tag: 'Disaster',
      orig: 'The death toll from the Himalayan floods has passed 1,000 in Nepal and Tibet, with more than 4,000 people still missing six days after the disaster.',
      ja: 'ヒマラヤの洪水による死者はネパールとチベットで1000人を超え、発生から6日を経てなお4000人以上の安否が分かっていない。' },
    { lang: 'en', tag: 'Justice',
      orig: 'A former gang member, Duane "Keffe D" Davis, has been found guilty of orchestrating the murder of the rapper Tupac Shakur, 30 years after the shooting.',
      ja: '元ギャング構成員のデュアン・"ケフィ・D"・デイビスが、ラッパーのトゥパック・シャクール殺害を首謀したとして有罪となった。事件から30年後の評決である。' },
    { lang: 'zh', tag: '航天',
      orig: '智神星一号运载火箭首飞成功，中国新型运载火箭完成首次飞行任务。',
      ja: '新型ロケット「智神星一号」が初飛行に成功し、中国の新しい打ち上げ機が最初の任務を完了した。' },
    { lang: 'zh', tag: '外交',
      orig: '习近平出席在比什凯克举行的上海合作组织成员国元首理事会第二十六次会议并发表讲话。',
      ja: '習近平国家主席がビシュケクで開かれた上海協力機構の首脳理事会第26回会議に出席し、演説を行った。' },
    { lang: 'es', tag: 'Deporte',
      orig: 'Messi se despide de la selección argentina tras 207 partidos y 125 goles, ambos récords absolutos del país.',
      ja: 'メッシがアルゼンチン代表に別れを告げた。207試合125得点は、いずれも同国の史上最多記録である。' },
    { lang: 'es', tag: 'Sociedad',
      orig: 'El curso escolar arranca en España con huelgas convocadas en Madrid, Cataluña y Andalucía, y tensiones en otras seis comunidades.',
      ja: 'スペインの新学年が始まった。マドリード、カタルーニャ、アンダルシアでストライキが予告され、他の6自治州でも緊張が続いている。' },
    { lang: 'fr', tag: 'Environnement',
      orig: 'En Chine, la capacité installée d\'énergie solaire dépasse pour la première fois celle des centrales à charbon.',
      ja: '中国で、太陽光発電の設備容量が初めて石炭火力を上回った。' },
    { lang: 'fr', tag: 'Sciences',
      orig: 'Pendant leur sommeil, les cachalots font des bulles pour flotter à l\'abri des vagues : des chercheurs ont découvert que ces animaux font la sieste à la verticale.',
      ja: 'マッコウクジラは眠るあいだ、波を避けて浮かぶために泡を出す ― 研究者たちは、この動物が垂直の姿勢で昼寝をすることを発見した。' }
  ],

  /* ── GLOBAL FEATURE ──────────────────────────────────── */
  feature: {
    title: '同じ日、四つの言語 ― 見出しはどこに枠を当てたか',
    sub: '9月1日のシーインを、EN / 中文 / ES / FR の報道はどう切り取ったか',
    body: [
      'この号の表紙記事は、ひとつの事実から始まりました。9月1日、シーインが香港で上場し、株価が下がった。それだけです。ところが、四つの言語の報道を並べてみると、同じ一日がまったく違う顔を見せます。',
      '英語（BBC）は「long-awaited stock market debut（待ち望まれた市場デビュー）」という枠を選びました。主語は市場であり、問われているのは投資家の判断です。記事の中心には、アナリストの「投資家は成長の再来を確信していない」という評価が置かれます。金融ジャーナリズムの視点です。',
      'スペイン語（El País / El Mundo）はもっと直截でした。「Shein cae hasta un 10% en su debut（デビューで最大10%下落）」。数字を見出しに立て、評価は読者に委ねる。動詞 caer（落ちる）ひとつで事実を伝えきる、簡潔な書き方です。',
      '中国語圏の報道（BBC中文）は「期待已久的股市首秀表現疲弱（待ち望まれた市場デビューは振るわなかった）」と、期待と結果の落差に焦点を当てました。中国発のグローバル企業がニューヨークにもロンドンにも受け入れられず、最終的に香港に落ち着いたという経緯 ― その文脈が読者に共有されているぶん、「疲弱（振るわない）」の一語が重く響きます。',
      'そしてフランス語（Le Monde）は、そもそも株式市場の話をしませんでした。同じ日の記事の主題は「Les pénalités financières sur les produits d\'ultrafast-fashion… entrent en vigueur mardi（超ファストファッション製品への課金が火曜に発効）」。シーインは投資対象ではなく、規制対象として登場します。枠組みは環境と消費文化であり、金融ではありません。',
      'どれかが正しく、どれかが間違っているのではありません。それぞれの社会が、その企業を何の話として受け取っているかが違うのです。英語圏では投資の話、スペイン語圏では市場の数字、中国語圏では自国企業の国際的な立ち位置、フランス語圏では使い捨て文化への規制。',
      '外国語を学ぶ最大の見返りは、語彙が増えることではなく、この「枠の違い」に自分で気づけるようになることです。翻訳を読んでいるかぎり、私たちは誰かがすでに選んだ枠のなかにいます。原文を読むというのは、枠を選び直す自由を手にすることにほかなりません。',
      '今週の4つの見出しを、下に並べておきます。声に出して読み比べてみてください。'
    ],
    compare: [
      { lang: 'en', orig: 'Shein shares fall in long-awaited stock market debut',
        ja: '待望の株式市場デビューでシーイン株が下落（BBC News）― 主語は「株」。焦点は市場の反応。' },
      { lang: 'zh', orig: 'Shein香港上市首日股价下跌　期待已久的股市首秀表现疲弱',
        ja: 'シーイン香港上場初日に株価下落 ― 待ち望まれた市場デビューは振るわず（BBC中文）― 「期待」と「疲弱」の落差を前面に。' },
      { lang: 'es', orig: 'Shein cae hasta un 10% en su debut en la Bolsa de Hong Kong',
        ja: 'シーイン、香港取引所デビューで最大10%下落（El País）― 数字が見出しの主役。評価語なし。' },
      { lang: 'fr', orig: 'Les pénalités financières sur les produits d\'ultrafast-fashion, visant Shein, Temu et AliExpress, entrent en vigueur mardi',
        ja: 'シーイン、テム、アリエクスプレスを狙った超ファストファッション製品への課金が火曜に発効（Le Monde）― 株の話は登場しない。' }
    ]
  },

  /* ── LANGUAGE LAB ────────────────────────────────────── */
  lab: [
    {
      lang: 'en', title: 'English Lab｜「上がる・下がる」の温度と、断定を避ける技術',
      items: [
        { term: 'soar / surge / climb / edge up ↔ plunge / slump / slide / dip / ease',
          ja: '英文経済記事は、変化の大きさを動詞そのもので表します。数字を読む前に、動詞から規模を予測できるようになるのが上級の読み方です。',
          examples: [{ o: 'Shares plunged 12% before easing to a 4% loss.', j: '株価は12%急落したあと、下げ幅は4%まで縮まった。' }] },
        { term: 'is expected to / is likely to / is due to',
          ja: 'それぞれ「見込まれている（根拠あり）」「ありそうだ（確率）」「予定されている（日程）」。報道はこの3つを厳密に使い分けます。日本語の「〜とみられる」に当たるのは is expected to です。',
          examples: [{ o: 'The figures are due out on Tuesday and are expected to show a record.', j: '数値は火曜公表の予定で、記録更新を示すとみられている。' }] },
        { term: 'not convinced / far from clear / it remains to be seen',
          ja: '「間違っている」と言わずに疑いを示す控えめな否定。英国メディアの文体を理解する鍵です。',
          examples: [{ o: 'It remains to be seen whether the malus changes anything.', j: 'その課金が何かを変えるのかは、まだ分からない。' }] },
        { term: 'as much as / more than / so far this year',
          ja: '数字に添える定型。as much as は「〜も」という驚き、more than はその数を含まない「超」、so far this year は「まだ年は終わっていない」という留保。',
          examples: [{ o: 'More than 40,000 names were put forward so far this year.', j: '今年これまでに4万件を超える名前が寄せられた。' }] },
        { term: 'on the back of / in the wake of / against the backdrop of',
          ja: 'いずれも「〜を受けて」。on the back of は勢いを引き継ぐ、in the wake of は（悪い）出来事の直後、against the backdrop of は背景事情。使い分けができると英作文が一気に大人びます。',
          examples: [{ o: 'The listing comes against the backdrop of tighter regulation in Europe.', j: 'この上場は、欧州で規制が強まるなかで行われた。' }] }
      ]
    },
    {
      lang: 'zh', title: '中文实验室｜日本人が落としやすい3つの穴',
      items: [
        { term: '① 同形異義語', pinyin: 'tóng xíng yì yì',
          ja: '表示（＝述べる）、结构（＝構成）、比重（＝割合）、力争（＝目指す）、会见（＝会談する）、培养（＝育てる）、检讨（＝反省する）。漢字が読めるぶん、日本人はかえって誤読します。「読める」と「分かる」は別物です。',
          examples: [{ o: '外交部表示，将继续关注此事。', j: '外務省は、引き続きこの件に注目していくと述べた。' }] },
        { term: '② 離合詞', pinyin: 'lí hé cí',
          ja: '留学・上课・排队・就业・见面・结婚・帮忙。動詞＋目的語で1語になっているため、①さらに目的語を取れない ②時間量は間に挟む、という2つの制約があります。',
          examples: [{ o: '他在中国留了三年学，跟很多人见了面。', j: '彼は中国に3年間留学し、多くの人と会った。' }] },
        { term: '③ 結果補語', pinyin: 'jié guǒ bǔ yǔ',
          ja: '学（学ぶ）と学会（習得する）、看（見る）と看懂（見て分かる）、买（買う）と买到（買えた）は別物です。中国語は「やった」と「できた」を必ず区別します。否定は 不 ではなく 没。',
          examples: [{ o: '我看了三遍，还是没看懂。', j: '3回読んだが、それでも理解できなかった。' }] },
        { term: '量詞のミニ辞典',
          ja: '条（細長い：河・路・鱼・消息）／所（施設：大学・医院）／家（企業：公司・餐厅）／名・位（人）／门（学科・言語）／片（薄いもの）／项（項目）／条 と 个 の使い分けが自然にできると、中国語らしさが一段上がります。',
          examples: [{ o: '这所大学开设了三门外语课程。', j: 'この大学は3つの外国語課程を開設している。' }] },
        { term: '書き言葉のスイッチ',
          ja: '据（〜によれば）、为（＝是）、截至（〜時点で）、即将（まもなく）、逐步（徐々に）、因此（したがって）。これらが出てきたら「書き言葉モード」です。会話に混ぜると硬すぎるので、読む語彙と話す語彙を分けて管理しましょう。',
          examples: [{ o: '据统计，截至7月底，装机容量为12.86亿千瓦。', j: '統計によれば、7月末時点で設備容量は12億8600万キロワットだった。' }] }
      ]
    },
    {
      lang: 'es', title: 'Laboratorio de español｜スペインと中南米、そして se',
      items: [
        { term: '地域差の見取り図',
          ja: 'ustedes ↔ vosotros（中南米には vosotros がない）／retiro ↔ retirada／computadora ↔ ordenador／penales ↔ penaltis／carro・auto ↔ coche。さらにアルゼンチンでは voseo（vos tenés, vos sos, vení）。教材のスペイン語だけでは、母語話者の半分としか話せません。',
          examples: [{ o: '¿Vos qué pensás? / ¿Tú qué piensas?', j: '君はどう思う？（亜／西）' }] },
        { term: '現在完了と点過去の地域差',
          ja: 'スペインでは今日の出来事に現在完了（Hoy he comido）、中南米では点過去（Hoy comí）。この記事の「le ha salido competencia」が現在完了であることは、それがスペインの新聞であることを示しています。時制が出身地を教えてくれます。' },
        { term: 'se の4つの顔',
          ja: '①再帰（se lava）②受動・非人称（se sirve, se habla）③相互（se conocieron）④le が変身した se（se lo dije）。加えて⑤強意（se comió toda la pizza）。日本人が最も混乱するのは④で、これは再帰とは無関係です。',
          examples: [{ o: 'Aquí se habla español y se come muy bien.', j: 'ここではスペイン語が話され、食事もとてもおいしい。' }] },
        { term: '受動態を避ける2つの方法',
          ja: '①3人称複数（Me robaron el móvil.＝携帯を盗まれた）②se（Se vende.＝売り出し中）。fue robado のような ser 受動態は、書き言葉以外ではほとんど使いません。日本語の受け身をそのまま ser で訳すと不自然になります。',
          examples: [{ o: 'Dicen que va a llover.', j: '雨が降るらしい。' }] },
        { term: '接続法が出る4つの場所',
          ja: '①未確定の先行詞（Busco a alguien que sepa chino）②感情・願望（Quiero que vengas）③否定・疑い（No creo que sea cierto）④aunque が仮定のとき（Aunque sea caro）。逆に言えば、事実を述べる文はすべて直説法です。',
          examples: [{ o: 'No hay nadie que lo entienda.', j: 'それを理解できる人は誰もいない。' }] }
      ]
    },
    {
      lang: 'fr', title: 'Laboratoire de français｜接続法・条件法・そして dont',
      items: [
        { term: 'il faut que + 接続法',
          ja: 'フランス語の接続法に出会う最も頻度の高い場面。必要・義務・願望・感情・疑い、そして bien que / pour que / avant que のあと。espérer que だけは直説法という例外も覚えておきましょう。',
          examples: [{ o: 'Il faut que chaque lycée adapte son règlement.', j: '各高校が校則を改める必要がある。' }] },
        { term: '時制の一致 ― 過去における未来',
          ja: '主節が過去なら、従属節の単純未来は条件法現在になります。Il a dit qu\'il viendrait.（来ると言った）。これは「もし〜なら」ではありません。フランス語のニュースを正確に読むための必須知識です。',
          examples: [{ o: 'Le ministre a concédé que ce serait difficile.', j: '大臣はそれが難しいだろうと認めた。' }] },
        { term: 'dont の見分けかた',
          ja: '元の文で de が必要なら dont。parler de → dont je parle／le volet de la loi → la loi dont le volet…／avoir besoin de → ce dont j\'ai besoin。日本人は où や que で代用してしまいがちです。',
          examples: [{ o: 'C\'est le film dont tout le monde parle.', j: 'それがみんなの話題になっている映画だ。' }] },
        { term: 'faire + 不定詞（使役）の語順',
          ja: 'faire renoncer les acheteurs（買い手に断念させる）。不定詞のすぐ後ろに意味上の主語が来ます。代名詞は faire の前（Il me fait rire.）。se faire + 不定詞は「〜される／〜してもらう」で、日本語の受け身に相当します。',
          examples: [{ o: 'Je me suis fait couper les cheveux.', j: '髪を切ってもらった。' }] },
        { term: 'depuis + 現在形',
          ja: 'J\'apprends le français depuis trois ans.（3年前からフランス語を学んでいる）。× J\'ai appris… は誤り。英語の現在完了に引きずられる、日本人学習者の最頻出ミスです。',
          examples: [{ o: 'Elle habite à Lyon depuis 2019.', j: '彼女は2019年からリヨンに住んでいる。' }] },
        { term: '組版の作法',
          ja: 'フランス語では「? ! ; :」の前と、ギユメ « » の内側に半角スペースを入れます。数字は小数点がカンマ（11,6）、桁区切りが空白（850 000）。書くときに真っ先に見られるところです。' }
      ]
    }
  ],

  /* ── REAL-WORLD CONVERSATION ─────────────────────────── */
  conversation: [
    { lang: 'en',
      q: 'Have you seen that Shein finally listed in Hong Kong?',
      qj: 'シーインがついに香港に上場したの、見ました？',
      a: 'I did, yes. Not the debut they were hoping for, by the look of it.',
      aj: '見ましたよ。見たところ、期待していたようなデビューではなかったですね。',
      note: 'by the look of it＝「見たところ」。断定を避けるイギリス英語らしい言い方です。Not the … they were hoping for は、否定を名詞句で表す簡潔な形。' },
    { lang: 'en',
      q: 'Do you buy from fast-fashion sites?',
      qj: 'ファストファッションのサイトで買い物しますか。',
      a: 'I used to, quite a lot. These days I try to think twice, though I would not say I have stopped.',
      aj: '以前はかなり買っていました。最近は一度考えるようにしています ― やめたとまでは言えませんが。',
      note: 'used to＝以前は〜していた（今は違う）。think twice＝よく考える。I would not say…＝「〜とまでは言わない」という、控えめに自分を訂正する便利な型です。' },
    { lang: 'zh',
      q: '你觉得为什么现在越来越多的人开始学中文？',
      qj: 'なぜ今、中国語を学ぶ人が増えているのだと思いますか。',
      a: '我想主要还是经济上的原因吧。工作上用得到，学起来就有动力了。',
      aj: '主にやはり経済的な理由でしょうね。仕事で使えるとなると、学ぶ動機も生まれますから。',
      note: '用得到＝「使う機会がある」（可能補語）。学起来＝「学んでみると」（方向補語の派生用法）。就有动力了＝「そうすればやる気が出る」。どれも会話で頻出する構造です。' },
    { lang: 'zh',
      q: '学外语最难的是什么？',
      qj: '外国語で一番難しいのは何ですか。',
      a: '对我来说是听力。看得懂，但是听不懂 —— 这种情况特别多。',
      aj: '私にとってはリスニングですね。読めば分かるのに、聞くと分からない ― そういうことが本当に多いんです。',
      note: '看得懂 / 听不懂 は可能補語。「見て理解できる／聞いて理解できない」を3文字で言い切れるのが中国語の強みです。对我来说＝私にとっては。' },
    { lang: 'es',
      q: '¿Te enteraste de lo de Messi?',
      qj: 'メッシの件、聞きました？',
      a: 'Sí, me dio pena. Pero después de veinte años, se lo ha ganado.',
      aj: 'ええ、切なかったです。でも20年やったんですから、それだけの資格はありますよ。',
      note: 'enterarse de＝〜を知る・耳にする。lo de + 名詞＝「〜の件」という便利な言い方。dar pena＝切なくさせる。ganárselo＝それに値することをしてきた。' },
    { lang: 'es',
      q: '¿Qué comida de tu país recomendarías?',
      qj: '自分の国の料理でおすすめは何ですか。',
      a: 'La okonomiyaki, sin duda. Es como una tortilla, pero con col. Y cada región la hace a su manera.',
      aj: '間違いなくお好み焼きですね。トルティージャみたいなものですが、キャベツが入っています。しかも地方ごとに作り方が違うんです。',
      note: 'Es como…（〜みたいなものです）は、自国の物を説明するときの最強の型。a su manera＝それぞれのやり方で。sin duda＝間違いなく。' },
    { lang: 'fr',
      q: 'Alors, cette rentrée ?',
      qj: 'で、新学期はどうですか。',
      a: 'Ça va, merci. Un peu dur de reprendre après trois semaines de vacances, mais on s\'y fait.',
      aj: 'まあまあです、ありがとう。3週間の休暇のあとに戻るのは少しきついですが、慣れますよ。',
      note: 'Alors, cette rentrée ? は9月のフランスで毎日交わされる挨拶です。on s\'y fait＝「（人は）それに慣れるものだ」。se faire à qqch＝〜に慣れる、の y は à ça を受けています。' },
    { lang: 'fr',
      q: 'Vous êtes plutôt pour ou contre l\'interdiction du portable ?',
      qj: '携帯禁止には、どちらかというと賛成ですか、反対ですか。',
      a: 'Plutôt pour, mais je me demande comment ils vont faire respecter ça au quotidien.',
      aj: 'どちらかといえば賛成です。ただ、日々どうやって守らせるつもりなのかは疑問ですね。',
      note: 'plutôt pour / plutôt contre＝「どちらかといえば賛成／反対」。je me demande + 間接疑問＝「〜だろうかと思う」。au quotidien＝日常的に。意見を柔らかく述べるフランス語の定型です。' }
  ],

  /* ── LISTENING & SHADOWING ───────────────────────────── */
  shadowing: [
    { lang: 'en',
      text: 'What stands out is not a single scorching afternoon but the sheer persistence of the heat.',
      ja: '際立っているのは、焼けつくような午後が一度あったことではなく、暑さがただひたすら続いたことのほうだ。',
      tip: 'not A but B の対比を、声の高さで作ってみましょう。not a single scorching afternoon を平坦に流し、but the SHEER PERSISTENCE で一段上げます。sheer の /ʃ/ と persistence の /s/ の連続が発音の山場です。' },
    { lang: 'en',
      text: 'Higher costs, tighter regulation and fiercer competition are all weighing on the company.',
      ja: 'コスト上昇、規制強化、競争激化がそろって同社の重荷になっている。',
      tip: '3つの比較級を同じリズムで並べるのがコツです（HIGH-er / TIGHT-er / FIERC-er）。英語は強勢のある音節の間隔をそろえようとする言語なので、この等間隔が「英語らしさ」の正体です。' },
    { lang: 'zh',
      text: '换句话说，光伏赢得的是"名义上的第一"，真正的较量还在后面。',
      ja: '言い換えれば、太陽光が手にしたのは「名目上の一位」であり、本当の勝負はこれからということだ。',
      tip: '「换句话说」で一度切り、「名义上的第一」を少し強めに。第三声が連続する「很好」型の変調に注意しつつ、「真正的较量还在后面」は落ち着いたトーンで下げて締めます。中国語の文末は下がるのが基本です。' },
    { lang: 'zh',
      text: '工作上的需要促使我学习中文。学会这门语言以后，我的生活条件改善了。',
      ja: '仕事上の必要が、私に中国語を学ばせました。この言語を身につけてから、生活の条件はよくなりました。',
      tip: '「学会」の会 huì（第四声）をはっきり落とすこと。学 xué（第二声）→ 会 huì（第四声）の上げてから落とす動きが、この2文字の要です。「以后」のあとに軽く間を置きます。' },
    { lang: 'es',
      text: 'Amo, amé y amaré siempre estar en la Selección.',
      ja: '代表にいることを、愛しているし、愛してきたし、これからもずっと愛し続ける。',
      tip: '3つの動詞を一息で。強勢は A-mo（第1音節）／a-MÉ（第2音節）／a-ma-RÉ（第3音節）と1つずつ後ろにずれていきます。この移動が原文のリズムそのものなので、そこだけは崩さずに読んでください。' },
    { lang: 'es',
      text: 'La idea surge del producto cercano, de lo que estamos acostumbrados a comer.',
      ja: '発想は地元の食材から、自分たちがふだん食べているものから来ています。',
      tip: 'de lo que… は一気につなげて「デロケ」と発音します。スペイン語は語と語のあいだで母音がくっつく言語（sinalefa）なので、単語ごとに切ると不自然になります。estamos acostumbrados の -os a- も1つにつながります。' },
    { lang: 'fr',
      text: 'Une école sans téléphone, c\'est retrouver la sérénité de l\'apprentissage.',
      ja: '携帯電話のない学校とは、学びの落ち着きを取り戻すことだ。',
      tip: 'Une_école のリエゾン［ユネコル］、de l\'apprentissage のアンシェヌマンに注意。カンマの前で軽く上げ、c\'est 以下で下げて着地させます。主題提示 → c\'est の型は、声に出すと構造が体で分かります。' },
    { lang: 'fr',
      text: 'Reste une question que la loi ne tranche pas : le malus fera-t-il renoncer les acheteurs ?',
      ja: '法律が答えを出していない問いが残る。この課金は買い手に購入をあきらめさせるのか。',
      tip: '倒置の Reste で始めるとき、文頭にわずかな溜めを作ります。fera-t-il の -t- は必ず発音（フェラティル）。疑問文の末尾は上がり調子で終えてください。フランス語の疑問イントネーションは日本語より明確に上がります。' }
  ],

  /* ── WEEKLY REVIEW（答えと解説つき）─────────────────── */
  review: [
    { lang: 'en',
      q: '空所を埋めてください：Shares fell ___ ___ ___ 10% before the losses eased.（「一時10%も下落した」）',
      hint: '驚きを表す3語です。',
      a: 'Shares fell as much as 10% before the losses eased.',
      aj: '株価は一時10%も下落したあと、下げ幅が縮まった。',
      why: 'as much as + 数値で「〜も」という驚きを表します。数えられる名詞なら as many as。なお fell 10% でも文法的には正しいのですが、「10%も」という書き手の評価は消えます。before は「そのあと」と前から訳すのが自然です。' },
    { lang: 'en',
      q: 'この文の構造を説明してください：It arrives on the back of what the Met Office is expected to confirm was the country\'s hottest summer.',
      hint: '挿入節を括弧でくくってみましょう。',
      a: 'It arrives on the back of [ what ( the Met Office is expected to confirm ) was the country\'s hottest summer ].',
      aj: '英気象庁が「国内史上最も暑い夏だった」と確認する見込みの、その夏を受けての到来である。',
      why: '連鎖関係詞節。( ) の挿入節を外すと what was the country\'s hottest summer という素直な形が現れます。what が節の主語を兼ね、was の主語になっています。この「挿入節を外して読む」手順を身につけると、英文ニュースの難文の大半が解けます。' },
    { lang: 'zh',
      q: '誤りを直してください：他在日本留学了三年。',
      hint: '留学 は離合詞です。',
      a: '他在日本留了三年学。',
      aj: '彼は日本に3年間留学した。',
      why: '留学 は 留＋学 という動詞＋目的語の構造（離合詞）なので、時間量は2字の間に挟みます。同じ規則で「2時間並んだ」は 排了两个小时的队、「4コマ授業を受けた」は 上了四节课。日本人学習者の頻出ミス第1位です。' },
    { lang: 'zh',
      q: '次の文の 表示 は日本語のどの語に当たりますか：气象部门表示，本周将有强降雨。',
      hint: '「ディスプレイに出す」ではありません。',
      a: '气象部门表示，本周将有强降雨。＝「気象当局は、今週は強い雨が降ると発表した」',
      aj: '気象当局は、今週は強い雨が降ると発表した。',
      why: '中国語の 表示 は「（人・組織が）意見や態度を述べる」。画面への「表示」は 显示 xiǎnshì です。同じ罠：结构（＝構成、「結構」ではない）、比重（＝割合）、力争（＝目指す）、会见（＝会談する）、检讨（＝反省する）。漢字が読めるからこそ危ない語群です。' },
    { lang: 'es',
      q: '接続法か直説法か選んでください：Busco a alguien que (sabe / sepa) chino.',
      hint: 'その人はもう見つかっていますか。',
      a: 'Busco a alguien que sepa chino.',
      aj: '中国語ができる人を探しています。',
      why: 'まだ見つかっていない＝先行詞が未確定なので接続法 sepa。すでに知っている特定の人なら直説法：Conozco a alguien que sabe chino.（中国語ができる人を知っている）。「その人は実在が確定しているか」が判断基準です。' },
    { lang: 'es',
      q: '「携帯を盗まれた」をスペイン語らしく書いてください。',
      hint: 'ser 受動態は使いません。',
      a: 'Me robaron el móvil.',
      aj: '携帯を盗まれた。',
      why: '直訳は「（誰かが）私に携帯を盗んだ」。3人称複数の非人称用法で、動作主が不明・不問のときの標準形です。Mi móvil fue robado. は文法的には正しくても、会話ではまず使いません。日本語の受け身＝スペイン語の3人称複数 or se、と覚えておきましょう。' },
    { lang: 'fr',
      q: '直してください：J\'ai appris le français depuis trois ans.',
      hint: '英語の現在完了に引きずられています。',
      a: 'J\'apprends le français depuis trois ans.',
      aj: '私は3年前からフランス語を学んでいる。',
      why: 'フランス語では depuis を現在形と組み合わせて「今も続いている」ことを表します。複合過去にすると「もう終わったこと」になってしまいます。過去のある時点まで続いていた場合は半過去：J\'apprenais le français depuis trois ans quand j\'ai déménagé.' },
    { lang: 'fr',
      q: '関係代名詞を入れてください：C\'est le film ___ tout le monde parle.',
      hint: '動詞 parler が要求する前置詞は？',
      a: 'C\'est le film dont tout le monde parle.',
      aj: 'それがみんなの話題になっている映画だ。',
      why: 'parler de qqch なので、de を含む関係代名詞 dont を使います。× le film que tout le monde parle は誤り。動詞が de を取るなら dont、à を取るなら auquel / à qui、何も取らないなら que ― この3択の判断が関係代名詞の核心です。' },
    { lang: 'fr',
      q: '時制の一致に直してください：Le ministre a concédé que ce sera difficile.',
      hint: '主節が過去です。',
      a: 'Le ministre a concédé que ce serait difficile.',
      aj: '大臣は、それが難しいだろうと認めた。',
      why: '主節が過去（a concédé）のとき、従属節の単純未来（sera）は条件法現在（serait）になります。これは仮定ではなく「過去から見た未来」。日本語には対応する形がないので、意識的に操作する必要があります。' },
    { lang: 'en',
      q: '4言語横断：「〜を受けて／〜にともない」を、英・中・西・仏でそれぞれ言ってみましょう。',
      hint: 'この号の記事すべてに出てきた表現です。',
      a: 'EN: on the back of ／ 中文: 随着 ／ ES: tras, a raíz de ／ FR: à la suite de, dans la foulée de',
      aj: '英：on the back of ／中：随着 ／西：tras・a raíz de ／仏：à la suite de・dans la foulée de',
      why: 'どの言語にも「先行する出来事を受けて」を表す定型があり、報道文の骨格を作っています。中国語の 随着 は後ろに〈…的＋名詞〉を取り、フランス語の dans la foulée de（〜の勢いを受けて）は英語の on the back of とほぼ同じ比喩です。言語をまたいで同じ機能の表現を集めると、記憶に定着しやすくなります。' }
  ]
});
